### PR TITLE
Migrate chat demo to V3

### PR DESCRIPTION
**Pull request by gravi2**
**Issue: #204**

**Description of changes:**
This PR updates the "chat" app with following:
1. Uninstall `amazon-chime-sdk-js` because it's already the peer dependency of `amazon-chime-sdk-component-library-react`
3. Add `@types/react` to avoid react types errors
4. Migrate to `amazon-chime-sdk-component-library-react` following the migration guide
5. Fix the 4 security alerts by running `npm audio fix`

**Testing**
1. How did you test these changes?
Make a e2e testing and verify the chat and meeting are working correctly.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, chat demo.
3. If applicable, have you run `npm run build` successfully locally to fix all warnings and errors? 
Yes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by devalevenkatesh — APPROVED** [review]
LGTM, So chat demo does not do any device selection?

**Comment by xuesichao** [comment]
>  So chat demo does not do any device selection?

Chat demo has device selections. They're implemented on top of SDK Components, so we don't need to migrate them.

**Comment by xuesichao** [comment]
@gravi2 Thanks for your help! Your contribution is greatly welcomed and appreciated!

**Comment by gravi2** [comment]
@xuesichao @ltrung  thank you for the merge!

**Pull request merged**
