### PR TITLE
fixes aws-samples/amazon-chime-sdk#45: Show attachment when recieving message via WebSocket

### PR DESCRIPTION
**Pull request by dpwspoon**
**Issue #45 :**

**Description of changes:**

**Testing**

1. How did you test these changes?

Launch demo, send message with attachement, confirm shows in chat.

2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it?

The chat demo

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ltrung** [comment]
Can we add more details on what the issue is and how you fix it?

**Comment by dpwspoon** [comment]
Issue was that attachments weren't displaying with realtime messages (i.e. on open channel).  Instead they just showed link to jpeg.  

This was broken with the introduction of meeting rings.  Both meeting rings and attachements use metadata.  Prior to this change attachments was inadvertently not being processed cause it had metadata.  With this change it will be processed and formatted.

**Comment by ltrung** [comment]
> Issue was that messages with attachments weren't displaying with realtime messages (i.e. on open channel).
> 
> This was broken with the introduction of meeting rings. Both meeting rings and attachements use metadata. The introduction of meeting rings originally added an `if(has meta data) { do stuff for meeting rings } else { process as normal } if check`. This inadvertently cause attachements to not be processed. With this change only meeting rings will do the meeting ring logic. Attachements will do normal processing and formatting.

Is this the PR #16 that introduces the meeting rings? Also I am not familiar with meeting rings. Is it a messaging concept? Can you link a doc that explains what it is?

**Review by ltrung — APPROVED** [review]

**Comment by dpwspoon** [comment]
yup and yes

**Pull request merged**
